# Generated by Django 3.0.4 on 2020-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='img/news', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
