# Generated by Django 3.0.4 on 2020-03-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='movies',
            new_name='movie',
        ),
    ]
