# Generated by Django 3.0.4 on 2020-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200324_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.FloatField(default=50.0, verbose_name='Цена'),
        ),
    ]
