# Generated by Django 3.0.4 on 2020-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('premiere_date', models.DateField(verbose_name='Дата примьеры')),
                ('poster', models.ImageField(upload_to='img/posters', verbose_name='Постер')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
