# Generated by Django 3.0.4 on 2020-03-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Age', verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='composers',
            field=models.ManyToManyField(to='movies.Composer', verbose_name='Компазитор'),
        ),
        migrations.AddField(
            model_name='movie',
            name='countrys',
            field=models.ManyToManyField(to='movies.Country', verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(to='movies.Producer', verbose_name='Продюсеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenwriters',
            field=models.ManyToManyField(to='movies.Screenwriter', verbose_name='Сценаристы'),
        ),
    ]
