# Generated by Django 3.0.4 on 2020-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200324_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='kek', max_length=100, verbose_name='Название кадра'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='photos',
        ),
        migrations.AddField(
            model_name='movie',
            name='photos',
            field=models.ManyToManyField(to='movies.Photo', verbose_name='Кадры фильма'),
        ),
    ]
