# Generated by Django 3.0.4 on 2020-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200324_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
