# Generated by Django 3.0.4 on 2020-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='composers',
            field=models.ManyToManyField(to='movies.Composer', verbose_name='Компазиторы'),
        ),
    ]
